from bs4 import BeautifulSoup   

def getData():
    data = """
<tbody>
    <tr>
        <td>黑暗物质</td>
        <td>本体</td>
        <td>任意</td>
        <td>1</td>
        <td>任意</td>
        <td>黑暗物质</td>
        <td></td>
        <td>任意</td>
        <td>任意</td>
        <td>1</td>
        <td>料理制作失败
        </td>
    </tr>
    <tr>
        <td>饭团</td>
        <td>本体</td>
        <td>料理台</td>
        <td>6</td>
        <td>海苔</td>
        <td>实惠、家常、素、饱腹、和风</td>
        <td></td>
        <td>5</td>
        <td>3</td>
        <td>1</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>海鲜味噌汤</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>8</td>
        <td>海苔</td>
        <td>实惠、家常、素、汤羹</td>
        <td>重油</td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>初始拥有
        </td>
    </tr>
    <tr>
        <td>司康饼</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>8</td>
        <td>黄油、面粉</td>
        <td>实惠、饱腹、西式</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>1</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>炙猪肉饭团</td>
        <td>本体</td>
        <td>料理台</td>
        <td>14</td>
        <td>猪肉</td>
        <td>实惠、家常、肉、饱腹、和风</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>2</td>
        <td>人间之里支线
        </td>
    </tr>
    <tr>
        <td>炒肉丝</td>
        <td>本体</td>
        <td>油锅</td>
        <td>15</td>
        <td>猪肉</td>
        <td>实惠、家常、肉、下酒、重油、中华</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>1</td>
        <td>博丽神社支线
        </td>
    </tr>
    <tr>
        <td>油豆腐</td>
        <td>本体</td>
        <td>油锅</td>
        <td>16</td>
        <td>豆腐</td>
        <td>实惠、家常、素、重油、和风</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>1</td>
        <td>上白泽慧音Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>露水煮蛋</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>18</td>
        <td>鸡蛋、露水</td>
        <td>实惠、清淡、生</td>
        <td>肉、水产、重油</td>
        <td>3</td>
        <td>1.8</td>
        <td>2</td>
        <td>莉格露Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>烤蘑菇</td>
        <td>本体</td>
        <td>烤架</td>
        <td>18</td>
        <td>蘑菇</td>
        <td>实惠、素、咸、灼热、菌类、烧烤</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>妖怪兽道支线
        </td>
    </tr>
    <tr>
        <td>豆腐锅</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>19</td>
        <td>豆腐</td>
        <td>实惠、素、清淡、灼热、和风</td>
        <td></td>
        <td>5</td>
        <td>3</td>
        <td>1</td>
        <td>茨木华扇Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>香炸蝉蜕</td>
        <td>本体</td>
        <td>油锅</td>
        <td>19</td>
        <td>蝉蜕</td>
        <td>实惠、重油、猎奇</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>1</td>
        <td>莉格露Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>猪肉盖浇饭</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>20</td>
        <td>猪肉</td>
        <td>家常、肉、饱腹</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>牛肉盖浇饭</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>20</td>
        <td>牛肉</td>
        <td>家常、肉、饱腹</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>茨木华扇Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>奶油炖菜</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>20</td>
        <td>洋葱、蘑菇、黄油</td>
        <td>素、菌类、汤羹、西式</td>
        <td></td>
        <td>9</td>
        <td>5.4</td>
        <td>2</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>月饼</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>20</td>
        <td>蜂蜜、面粉、糯米、月光草</td>
        <td>饱腹、小巧、甜、不可思议、文化底蕴、中华</td>
        <td></td>
        <td>10</td>
        <td>6</td>
        <td>5</td>
        <td>－
        </td>
    </tr>
    <tr>
        <td>凉菜雕花</td>
        <td>本体</td>
        <td>料理台</td>
        <td>20</td>
        <td>萝卜</td>
        <td>素、清淡、凉爽、适合拍照</td>
        <td>肉、灼热</td>
        <td>5</td>
        <td>3</td>
        <td>1</td>
        <td>比那名居天子Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>豆腐味噌</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>21</td>
        <td>豆腐</td>
        <td>家常、素、清淡、汤羹、和风</td>
        <td>重油</td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>稗田阿求Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>冷豆腐</td>
        <td>本体</td>
        <td>料理台</td>
        <td>21</td>
        <td>豆腐、萝卜</td>
        <td>家常、素、下酒、清淡、小巧</td>
        <td></td>
        <td>5</td>
        <td>3</td>
        <td>2</td>
        <td>初始拥有
        </td>
    </tr>
    <tr>
        <td>煮豆腐</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>22</td>
        <td>豆腐</td>
        <td>家常、素、清淡</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>1</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>土豆可乐饼</td>
        <td>本体</td>
        <td>油锅</td>
        <td>22</td>
        <td>土豆</td>
        <td>家常、素、重油</td>
        <td>凉爽</td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>热松饼</td>
        <td>本体</td>
        <td>油锅</td>
        <td>22</td>
        <td>鸡蛋、蜂蜜、面粉</td>
        <td>饱腹、甜、西式</td>
        <td></td>
        <td>9</td>
        <td>5.4</td>
        <td>2</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>烤八目鳗</td>
        <td>本体</td>
        <td>烤架</td>
        <td>22</td>
        <td>八目鳗</td>
        <td>招牌、水产、烧烤</td>
        <td>肉、素</td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>初始拥有
        </td>
    </tr>
    <tr>
        <td>臭豆腐</td>
        <td>本体</td>
        <td>油锅</td>
        <td>24</td>
        <td>豆腐、辣椒</td>
        <td>素、辣、猎奇、中华</td>
        <td>甜、果味</td>
        <td>5</td>
        <td>3</td>
        <td>1</td>
        <td>露米娅Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>炸猪肉排</td>
        <td>本体</td>
        <td>油锅</td>
        <td>25</td>
        <td>猪肉</td>
        <td>家常、肉、饱腹、重油</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>伊吹萃香Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>竹笋炒肉</td>
        <td>本体</td>
        <td>油锅</td>
        <td>25</td>
        <td>猪肉、竹笋</td>
        <td>家常、肉、下酒</td>
        <td></td>
        <td>10</td>
        <td>6</td>
        <td>2</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>北极甜虾蜜桃色拉</td>
        <td>本体</td>
        <td>料理台</td>
        <td>25</td>
        <td>虾、桃子、冰块</td>
        <td>素、水产、清淡、甜、果味、不可思议、适合拍照</td>
        <td>肉、咸</td>
        <td>10</td>
        <td>6</td>
        <td>2</td>
        <td>比那名居天子Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>猪肉鳟鱼熏</td>
        <td>本体</td>
        <td>烤架</td>
        <td>26</td>
        <td>鳟鱼、猪肉</td>
        <td>家常、肉、水产、烧烤</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>橙Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>炸八目鳗</td>
        <td>本体</td>
        <td>油锅</td>
        <td>27</td>
        <td>八目鳗</td>
        <td>招牌、水产、重油</td>
        <td>凉爽</td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>露米娅Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>麻薯</td>
        <td>本体</td>
        <td>料理台</td>
        <td>30</td>
        <td>糯米</td>
        <td>小巧、甜、和风</td>
        <td>肉、水产、咸、鲜</td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>因幡帝Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>温暖饭团</td>
        <td>本体</td>
        <td>料理台</td>
        <td>30</td>
        <td>鳟鱼、洋葱</td>
        <td>家常、素、水产、饱腹、灼热、和风</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>博丽灵梦Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>秘制小鱼干</td>
        <td>本体</td>
        <td>料理台</td>
        <td>30</td>
        <td>鳟鱼</td>
        <td>水产、小巧、咸、鲜</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>橙Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>麻婆豆腐</td>
        <td>本体</td>
        <td>油锅</td>
        <td>32</td>
        <td>猪肉、豆腐、辣椒</td>
        <td>素、辣、灼热、中华</td>
        <td>甜、果味、凉爽</td>
        <td>6</td>
        <td>3.6</td>
        <td>2</td>
        <td>藤原妹红Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>力量汤</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>34</td>
        <td>野猪肉、海苔</td>
        <td>肉、山珍、灼热、力量涌现、汤羹</td>
        <td>小巧、凉爽</td>
        <td>12</td>
        <td>7.2</td>
        <td>3</td>
        <td>橙Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>汤圆</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>35</td>
        <td>糯米</td>
        <td>家常、素、文化底蕴、中华</td>
        <td></td>
        <td>5</td>
        <td>3</td>
        <td>2</td>
        <td>香霖堂兑换（银色的青蛙硬币*5）
        </td>
    </tr>
    <tr>
        <td>水饺</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>35</td>
        <td>面粉</td>
        <td>家常、素、文化底蕴、中华</td>
        <td></td>
        <td>5</td>
        <td>3</td>
        <td>2</td>
        <td>香霖堂兑换（银色的青蛙硬币*5）
        </td>
    </tr>
    <tr>
        <td>班尼迪克蛋</td>
        <td>本体</td>
        <td>油锅</td>
        <td>35</td>
        <td>竹笋、鸡蛋、黄油、面粉</td>
        <td>饱腹、小巧、生、西式</td>
        <td>甜、果味</td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>帕秋莉Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>杂炊</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>40</td>
        <td>鳟鱼、豆腐、海苔</td>
        <td>家常、肉、鲜、灼热</td>
        <td></td>
        <td>5</td>
        <td>3</td>
        <td>2</td>
        <td>博丽灵梦Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>竹筒蒸蛋</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>40</td>
        <td>海苔、蘑菇、鸡蛋、竹子</td>
        <td>家常、清淡、菌类</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>2</td>
        <td>蓬莱山辉夜Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>流水素面</td>
        <td>本体</td>
        <td>料理台</td>
        <td>40</td>
        <td>面粉、竹子</td>
        <td>素、清淡、凉爽、不可思议</td>
        <td>重油</td>
        <td>7</td>
        <td>4.2</td>
        <td>3</td>
        <td>迷途竹林支线
        </td>
    </tr>
    <tr>
        <td>红烧鳗鱼</td>
        <td>本体</td>
        <td>油锅</td>
        <td>42</td>
        <td>八目鳗、洋葱</td>
        <td>招牌、素、水产、重油、鲜</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>红美铃Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>樱落雪</td>
        <td>本体</td>
        <td>本体</td>
        <td>料理台</td>
        <td>50</td>
        <td>极上金枪鱼</td>
        <td>水产、小巧、高级、生、海味、适合拍照、和风</td>
        <td>重油</td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>稗田阿求Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>能量串</td>
        <td>本体</td>
        <td>烤架</td>
        <td>50</td>
        <td>牛肉、洋葱、南瓜</td>
        <td>肉、饱腹、烧烤</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>3</td>
        <td>伊吹萃香Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>桃花羹</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>55</td>
        <td>桃子、露水、冰块</td>
        <td>素、甜、果味、凉爽、适合拍照、汤羹</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>比那名居天子Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>真·海鲜味噌汤</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>55</td>
        <td>鳟鱼、三文鱼</td>
        <td>家常、水产、清淡、汤羹</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>琪露诺Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>白桃生八桥</td>
        <td>本体</td>
        <td>料理台</td>
        <td>55</td>
        <td>桃子、糯米</td>
        <td>甜、果味、和风</td>
        <td>肉、水产、咸、鲜</td>
        <td>5</td>
        <td>3</td>
        <td>2</td>
        <td>因幡帝Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>蔬菜专辑</td>
        <td>本体</td>
        <td>料理台</td>
        <td>56</td>
        <td>土豆、洋葱、南瓜</td>
        <td>素、清淡、生、凉爽</td>
        <td>肉、水产、灼热</td>
        <td>5</td>
        <td>3</td>
        <td>3</td>
        <td>稗田阿求Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>香煎三文鱼</td>
        <td>本体</td>
        <td>油锅</td>
        <td>58</td>
        <td>三文鱼、竹笋</td>
        <td>肉、鲜、西式</td>
        <td></td>
        <td>10</td>
        <td>6</td>
        <td>3</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>豚骨拉面</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>60</td>
        <td>猪肉、海苔、鸡蛋</td>
        <td>家常、肉、饱腹、咸</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>升级
        </td>
    </tr>
    <tr>
        <td>诗礼银杏</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>60</td>
        <td>白果、蜂蜜</td>
        <td>素、甜、文化底蕴、中华</td>
        <td>咸</td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>上白泽慧音Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>黄油牛排</td>
        <td>本体</td>
        <td>油锅</td>
        <td>60</td>
        <td>和牛、黄油</td>
        <td>肉、饱腹、重油、西式</td>
        <td>甜、凉爽</td>
        <td>7</td>
        <td>4.2</td>
        <td>2</td>
        <td>红魔馆主线
        </td>
    </tr>
    <tr>
        <td>猩红恶魔蛋糕</td>
        <td>本体</td>
        <td>料理台</td>
        <td>60</td>
        <td>土豆、南瓜、蜂蜜、露水</td>
        <td>甜、梦幻、猎奇、适合拍照、西式</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>妖怪兽道三妖精处购买
        </td>
    </tr>
    <tr>
        <td>无意识妖怪慕斯</td>
        <td>本体</td>
        <td>料理台</td>
        <td>60</td>
        <td>豆腐、洋葱、蜂蜜、黄油</td>
        <td>高级、甜、梦幻、适合拍照、西式</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>妖怪兽道三妖精处购买
        </td>
    </tr>
    <tr>
        <td>白果萝卜排骨汤</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>65</td>
        <td>猪肉、萝卜、白果</td>
        <td>昂贵、肉、灼热、汤羹、中华</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>2</td>
        <td>红美铃Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>竹取姬</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>65</td>
        <td>黑毛猪肉、松露、竹笋、白果、竹子</td>
        <td>昂贵、肉、高级、传说、适合拍照、文化底蕴、特产、和风</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>竹林主线，藤原妹红
        </td>
    </tr>
    <tr>
        <td>不死鸟</td>
        <td>本体</td>
        <td>烤架</td>
        <td>65</td>
        <td>土豆、洋葱、萝卜、蜂蜜、面粉</td>
        <td>昂贵、高级、传说、燃起来了、适合拍照、烧烤、西式</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>竹林主线，蓬莱山辉夜
        </td>
    </tr>
    <tr>
        <td>野味加农</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>66</td>
        <td>黑毛猪肉、土豆、南瓜</td>
        <td>昂贵、肉、饱腹、重油、山珍、灼热</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>4</td>
        <td>茨木华扇Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>月之恋人</td>
        <td>本体</td>
        <td>料理台</td>
        <td>66</td>
        <td>鸡蛋、黄油、面粉、月光草</td>
        <td>昂贵、小巧、甜、适合拍照、特产</td>
        <td>肉、素、水产</td>
        <td>10</td>
        <td>6</td>
        <td>3</td>
        <td>蓬莱山辉夜Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>水煮鱼</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>68</td>
        <td>鳟鱼、辣椒</td>
        <td>昂贵、水产、辣、灼热、燃起来了、中华</td>
        <td>肉、甜、果味、凉爽</td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>藤原妹红Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>意式烩饭</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>70</td>
        <td>洋葱、蘑菇、竹笋、黄油</td>
        <td>昂贵、饱腹、鲜、菌类、西式</td>
        <td>甜</td>
        <td>6</td>
        <td>3.6</td>
        <td>2</td>
        <td>帕秋莉Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>赛熊掌</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>70</td>
        <td>河豚、黑毛猪肉、竹笋</td>
        <td>昂贵、肉、水产、高级、鲜、山珍、不可思议、力量涌现</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>3</td>
        <td>露米娅Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>蜜汁叉烧</td>
        <td>本体</td>
        <td>烤架</td>
        <td>70</td>
        <td>猪肉、蜂蜜</td>
        <td>昂贵、肉、重油、甜、不可思议、中华</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>3</td>
        <td>红魔馆支线
        </td>
    </tr>
    <tr>
        <td>毛玉三色冰激凌</td>
        <td>本体</td>
        <td>料理台</td>
        <td>75</td>
        <td>豆腐、鸡蛋、蜂蜜、露水</td>
        <td>昂贵、甜、凉爽、梦幻、适合拍照、西式</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>妖怪兽道萌澄果处购买
        </td>
    </tr>
    <tr>
        <td>幻昙花糕</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>78</td>
        <td>幻昙华、露水</td>
        <td>昂贵、高级、传说、甜、梦幻、适合拍照</td>
        <td>肉、水产</td>
        <td>7</td>
        <td>4.2</td>
        <td>3</td>
        <td>莉格露Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>猪鹿蝶</td>
        <td>本体</td>
        <td>蒸锅</td>
        <td>78</td>
        <td>鹿肉、野猪肉、月光草</td>
        <td>昂贵、肉、高级、适合拍照、文化底蕴</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>琪露诺Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>月光团子</td>
        <td>本体</td>
        <td>料理台</td>
        <td>80</td>
        <td>糯米、月光草</td>
        <td>昂贵、甜、不可思议、特产、和风</td>
        <td>肉、水产、咸、鲜</td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>因幡帝Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>毛玉熔岩豆腐</td>
        <td>本体</td>
        <td>料理台</td>
        <td>85</td>
        <td>牛肉、豆腐、洋葱、辣椒</td>
        <td>昂贵、素、鲜、不可思议、适合拍照、中华</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>妖怪兽道萌澄果处购买
        </td>
    </tr>
    <tr>
        <td>刺身拼盘</td>
        <td>本体</td>
        <td>料理台</td>
        <td>88</td>
        <td>三文鱼、金枪鱼</td>
        <td>昂贵、水产、高级、生、适合拍照、和风</td>
        <td>灼热</td>
        <td>5</td>
        <td>3</td>
        <td>3</td>
        <td>琪露诺Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>二天一流</td>
        <td>本体</td>
        <td>烤架</td>
        <td>90</td>
        <td>野猪肉、黑毛猪肉</td>
        <td>昂贵、肉、高级、山珍、燃起来了、文化底蕴、烧烤</td>
        <td>家常</td>
        <td>18</td>
        <td>10.8</td>
        <td>4</td>
        <td>伊吹萃香Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>白雪</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>98</td>
        <td>八目鳗、河豚、海苔</td>
        <td>昂贵、肉、水产、高级、文化底蕴、和风</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>上白泽慧音Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>大奢宴</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>105</td>
        <td>河豚、黑毛猪肉、和牛</td>
        <td>昂贵、肉、水产、饱腹、高级、山珍</td>
        <td>实惠、家常</td>
        <td>10</td>
        <td>6</td>
        <td>3</td>
        <td>博丽灵梦Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>岩浆</td>
        <td>本体</td>
        <td>煮锅</td>
        <td>125</td>
        <td>河豚、牛肉、和牛、松露</td>
        <td>昂贵、肉、水产、饱腹、高级、灼热、力量涌现、菌类</td>
        <td>凉爽</td>
        <td>8</td>
        <td>4.8</td>
        <td>3</td>
        <td>藤原妹红Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>蓬莱玉枝</td>
        <td>本体</td>
        <td>烤架</td>
        <td>125</td>
        <td>三文鱼、猪肉、鹿肉、和牛、竹子</td>
        <td>昂贵、肉、高级、传说、文化底蕴、烧烤</td>
        <td></td>
        <td>13</td>
        <td>7.8</td>
        <td>5</td>
        <td>蓬莱山辉夜Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>华光玉煎包</td>
        <td>本体</td>
        <td>油锅</td>
        <td>128</td>
        <td>黑毛猪肉、蘑菇</td>
        <td>昂贵、肉、高级、传说、梦幻、菌类、中华</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>4</td>
        <td>红美铃Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>惠灵顿牛排</td>
        <td>本体</td>
        <td>油锅</td>
        <td>150</td>
        <td>和牛、松露、鸡蛋、黄油、面粉</td>
        <td>昂贵、肉、高级、传说、山珍、西式</td>
        <td>甜、凉爽</td>
        <td>14</td>
        <td>8.4</td>
        <td>4</td>
        <td>帕秋莉Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>腌黄瓜</td>
        <td>DLC 1</td>
        <td>料理台</td>
        <td>16</td>
        <td>黄瓜、黑盐</td>
        <td>实惠、素、下酒、小巧、咸</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>河城荷取Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>蘑菇肉片</td>
        <td>DLC 1</td>
        <td>油锅</td>
        <td>20</td>
        <td>猪肉、蘑菇</td>
        <td>家常、肉、重油、菌类</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>雾雨魔理沙Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>炸虾天妇罗</td>
        <td>DLC 1</td>
        <td>油锅</td>
        <td>22</td>
        <td>虾、面粉</td>
        <td>下酒、重油</td>
        <td>清淡</td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>犬走椛Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>大阪烧</td>
        <td>DLC 1</td>
        <td>油锅</td>
        <td>24</td>
        <td>萝卜、鸡蛋、面粉</td>
        <td>招牌、小巧、适合拍照、和风</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>2</td>
        <td>东风谷早苗Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>奶香蘑菇汤</td>
        <td>DLC 1</td>
        <td>煮锅</td>
        <td>28</td>
        <td>土豆、蘑菇、奶油</td>
        <td>家常、适合拍照、菌类</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>1</td>
        <td>爱丽丝Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>手握寿司</td>
        <td>DLC 1</td>
        <td>料理台</td>
        <td>28</td>
        <td>三文鱼、金枪鱼</td>
        <td>水产、清淡、鲜、生、文化底蕴、和风</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>矢田寺成美Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>章鱼烧</td>
        <td>DLC 1</td>
        <td>油锅</td>
        <td>36</td>
        <td>海苔、面粉、章鱼</td>
        <td>招牌、水产、饱腹、小巧、适合拍照</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>东风谷早苗Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>黄金酥鱼饼</td>
        <td>DLC 1</td>
        <td>油锅</td>
        <td>40</td>
        <td>鳟鱼、蜂蜜、面粉</td>
        <td>水产、下酒、重油、力量涌现</td>
        <td></td>
        <td>9</td>
        <td>5.4</td>
        <td>2</td>
        <td>犬走椛Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>南瓜虾盅</td>
        <td>DLC 1</td>
        <td>蒸锅</td>
        <td>55</td>
        <td>虾、豆腐、南瓜</td>
        <td>水产、饱腹、清淡、甜、鲜、适合拍照、特产</td>
        <td></td>
        <td>9</td>
        <td>5.4</td>
        <td>2</td>
        <td>矢田寺成美Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>普通小蛋糕</td>
        <td>DLC 1</td>
        <td>蒸锅</td>
        <td>56</td>
        <td>鸡蛋、葡萄、奶油</td>
        <td>高级、甜、果味、适合拍照、文化底蕴</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>爱丽丝Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>秘制鲜菌煲</td>
        <td>DLC 1</td>
        <td>煮锅</td>
        <td>62</td>
        <td>蘑菇、松露、露水</td>
        <td>昂贵、鲜、菌类、特产、和风</td>
        <td></td>
        <td>9</td>
        <td>5.4</td>
        <td>3</td>
        <td>雾雨魔理沙Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>奶油焗蟹</td>
        <td>DLC 1</td>
        <td>油锅</td>
        <td>88</td>
        <td>螃蟹、奶油</td>
        <td>昂贵、招牌、下酒、高级、鲜、海味、适合拍照</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>3</td>
        <td>河城荷取Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>七色羊羹</td>
        <td>DLC 1</td>
        <td>蒸锅</td>
        <td>92</td>
        <td>海苔、幻昙华、露水、葡萄</td>
        <td>昂贵、高级、甜、果味、梦幻、不可思议、适合拍照、文化底蕴</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>4</td>
        <td>爱丽丝Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>海胆刺身</td>
        <td>DLC 1</td>
        <td>料理台</td>
        <td>108</td>
        <td>露水、海胆</td>
        <td>昂贵、小巧、高级、甜、海味、不可思议、适合拍照、特产</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>4</td>
        <td>东风谷早苗Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>蘑女的舞踏烩</td>
        <td>DLC 1</td>
        <td>煮锅</td>
        <td>112</td>
        <td>虾、蘑菇、辣椒、章鱼</td>
        <td>昂贵、水产、重油、辣、咸、鲜、灼热、适合拍照、菌类</td>
        <td></td>
        <td>14</td>
        <td>8.4</td>
        <td>4</td>
        <td>雾雨魔理沙Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>全肉盛宴</td>
        <td>DLC 1</td>
        <td>烤架</td>
        <td>115</td>
        <td>鹿肉、野猪肉、黑毛猪肉、和牛</td>
        <td>昂贵、肉、下酒、大份、高级、咸、山珍、灼热、适合拍照</td>
        <td></td>
        <td>14</td>
        <td>8.4</td>
        <td>4</td>
        <td>犬走椛Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>拟尻子玉</td>
        <td>DLC 1</td>
        <td>煮锅</td>
        <td>120</td>
        <td>鹿肉、松露、蝉蜕</td>
        <td>昂贵、下酒、小巧、传说、梦幻、猎奇、灼热</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>河城荷取Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>幻想佛跳墙</td>
        <td>DLC 1</td>
        <td>煮锅</td>
        <td>160</td>
        <td>极上金枪鱼、河豚、黑毛猪肉、和牛、松露</td>
        <td>昂贵、肉、水产、高级、传说、山珍、力量涌现、适合拍照、文化底蕴、菌类、特产、中华</td>
        <td></td>
        <td>18</td>
        <td>10.8</td>
        <td>4</td>
        <td>矢田寺成美Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>丧气芝士条</td>
        <td>DLC 2</td>
        <td>蒸锅</td>
        <td>25</td>
        <td>白果、白果、芝士</td>
        <td>下酒、咸、鲜、特产</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>水桥帕露西Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>芝士蛋</td>
        <td>DLC 2</td>
        <td>油锅</td>
        <td>26</td>
        <td>鸡蛋、芝士</td>
        <td>重油、咸、鲜、生</td>
        <td>肉</td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>灵乌路空Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>猫饭</td>
        <td>DLC 2</td>
        <td>料理台</td>
        <td>26</td>
        <td>鳟鱼、露水、面粉</td>
        <td>水产、小巧、鲜</td>
        <td>重油</td>
        <td>5</td>
        <td>3</td>
        <td>1</td>
        <td>火焰猫燐Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>狮子头</td>
        <td>DLC 2</td>
        <td>煮锅</td>
        <td>28</td>
        <td>牛肉</td>
        <td>招牌、肉、下酒、鲜、特产</td>
        <td>水产、饱腹</td>
        <td>7</td>
        <td>4.2</td>
        <td>1</td>
        <td>星熊勇仪Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>樱花布丁</td>
        <td>DLC 2</td>
        <td>蒸锅</td>
        <td>32</td>
        <td>桃子、蜂蜜</td>
        <td>小巧、甜、果味、凉爽、适合拍照、特产</td>
        <td>重油、咸</td>
        <td>6</td>
        <td>3.6</td>
        <td>2</td>
        <td>古明地觉Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>阴郁水果派</td>
        <td>DLC 2</td>
        <td>料理台</td>
        <td>36</td>
        <td>葡萄、柠檬、芝士</td>
        <td>酸、咸、鲜、果味、特产</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>水桥帕露西Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>提神布丁</td>
        <td>DLC 2</td>
        <td>蒸锅</td>
        <td>42</td>
        <td>葡萄、葡萄、柠檬</td>
        <td>小巧、酸、甜、果味、凉爽、力量涌现</td>
        <td>重油、咸</td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>古明地觉Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>脆旋风</td>
        <td>DLC 2</td>
        <td>料理台</td>
        <td>42</td>
        <td>蜂蜜、蝉蜕、面粉</td>
        <td>饱腹、生、猎奇、特产</td>
        <td>重油</td>
        <td>5</td>
        <td>3</td>
        <td>1</td>
        <td>黑谷山女Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>三文鱼天妇罗</td>
        <td>DLC 2</td>
        <td>油锅</td>
        <td>44</td>
        <td>三文鱼、鸡蛋、黄油、面粉</td>
        <td>水产、重油、小巧、高级、鲜</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>火焰猫燐Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>巨人玉子烧</td>
        <td>DLC 2</td>
        <td>油锅</td>
        <td>60</td>
        <td>鸡蛋、鸡蛋、面粉、面粉</td>
        <td>饱腹、高级、甜、力量涌现、和风</td>
        <td>下酒</td>
        <td>12</td>
        <td>7.2</td>
        <td>2</td>
        <td>星熊勇仪Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>一击☆必杀</td>
        <td>DLC 2</td>
        <td>烤架</td>
        <td>62</td>
        <td>鹿肉、野猪肉、洋葱</td>
        <td>昂贵、肉、饱腹、重油、山珍、力量涌现、烧烤</td>
        <td></td>
        <td>9</td>
        <td>5.4</td>
        <td>3</td>
        <td>灵乌路空Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>仰望天花板派</td>
        <td>DLC 2</td>
        <td>蒸锅</td>
        <td>66</td>
        <td>鳟鱼、桃子、面粉</td>
        <td>昂贵、招牌、下酒、海味、猎奇、适合拍照、特产</td>
        <td>肉</td>
        <td>9</td>
        <td>5.4</td>
        <td>2</td>
        <td>黑谷山女Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>燃尽布丁</td>
        <td>DLC 2</td>
        <td>蒸锅</td>
        <td>73</td>
        <td>蜂蜜、葡萄、柠檬、柠檬</td>
        <td>昂贵、招牌、小巧、酸、甜、果味、凉爽、梦幻、力量涌现</td>
        <td>重油、咸</td>
        <td>8</td>
        <td>4.8</td>
        <td>4</td>
        <td>古明地觉Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>绝叫关东煮</td>
        <td>DLC 2</td>
        <td>煮锅</td>
        <td>92</td>
        <td>牛肉、豆腐、萝卜、辣椒、辣椒</td>
        <td>昂贵、肉、饱腹、大份、高级、辣、鲜、灼热、力量涌现、特产</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>水桥帕露西Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>兜甲蒸糕</td>
        <td>DLC 2</td>
        <td>蒸锅</td>
        <td>105</td>
        <td>黑毛猪肉、蜂蜜、蝉蜕、面粉</td>
        <td>昂贵、招牌、饱腹、高级、鲜、生、猎奇、力量涌现、适合拍照、特产</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>3</td>
        <td>黑谷山女Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>地狱激辛警告！</td>
        <td>DLC 2</td>
        <td>油锅</td>
        <td>108</td>
        <td>牛肉、辣椒、辣椒、辣椒、芝士</td>
        <td>昂贵、肉、重油、辣、咸、猎奇、灼热、力量涌现、适合拍照</td>
        <td>素、清淡</td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>灵乌路空Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>鱼跃龙门</td>
        <td>DLC 2</td>
        <td>蒸锅</td>
        <td>142</td>
        <td>极上金枪鱼、鹿肉、松露、蜂蜜、月光草</td>
        <td>昂贵、肉、水产、大份、高级、甜、鲜、海味、梦幻、文化底蕴、菌类、中华</td>
        <td></td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>火焰猫燐Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>大江户船祭</td>
        <td>DLC 2</td>
        <td>料理台</td>
        <td>206</td>
        <td>鳟鱼、三文鱼、金枪鱼、极上金枪鱼、冰块</td>
        <td>昂贵、招牌、水产、下酒、高级、传说、鲜、生、海味、适合拍照、文化底蕴、和风</td>
        <td></td>
        <td>24</td>
        <td>14.4</td>
        <td>4</td>
        <td>星熊勇仪Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>云山棉花糖</td>
        <td>DLC 3</td>
        <td>油锅</td>
        <td>20</td>
        <td>桃子、蜂蜜</td>
        <td>甜、果味、不可思议、特产</td>
        <td>肉、咸</td>
        <td>8</td>
        <td>4.8</td>
        <td>1</td>
        <td>封兽鵺Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>烤地瓜</td>
        <td>DLC 3</td>
        <td>烤架</td>
        <td>25</td>
        <td>地瓜</td>
        <td>实惠、家常、饱腹、甜</td>
        <td>下酒</td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>多多良小伞Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>比斯开湾饼干</td>
        <td>DLC 3</td>
        <td>烤架</td>
        <td>26</td>
        <td>面粉、芝士</td>
        <td>饱腹、咸、灼热</td>
        <td>酸</td>
        <td>5</td>
        <td>3</td>
        <td>1</td>
        <td>村纱水蜜Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>拔丝地瓜</td>
        <td>DLC 3</td>
        <td>油锅</td>
        <td>30</td>
        <td>蜂蜜、地瓜</td>
        <td>家常、素、饱腹、甜</td>
        <td>生</td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>苏我屠自古Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>蜜饯栗子</td>
        <td>DLC 3</td>
        <td>料理台</td>
        <td>30</td>
        <td>蜂蜜、板栗</td>
        <td>小巧、甜、特产</td>
        <td></td>
        <td>6</td>
        <td>3.6</td>
        <td>1</td>
        <td>霍青娥Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>瘦马团子</td>
        <td>DLC 3</td>
        <td>料理台</td>
        <td>45</td>
        <td>糯米、糯米</td>
        <td>饱腹、猎奇、适合拍照、文化底蕴</td>
        <td>肉</td>
        <td>9</td>
        <td>5.4</td>
        <td>2</td>
        <td>多多良小伞Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>松子糕</td>
        <td>蒸锅</td>
        <td>46</td>
        <td>糯米、松子</td>
        <td>清淡、特产</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>物部布都Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>天师板栗焖菇</td>
        <td>DLC 3</td>
        <td>煮锅</td>
        <td>55</td>
        <td>蘑菇、松露、板栗</td>
        <td>家常、素、菌类、特产、中华</td>
        <td></td>
        <td>8</td>
        <td>4.8</td>
        <td>2</td>
        <td>霍青娥Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>圣白莲子糕</td>
        <td>DLC 3</td>
        <td>蒸锅</td>
        <td>56</td>
        <td>白果、黄油、面粉、莲子</td>
        <td>素、清淡、小巧、适合拍照、特产</td>
        <td>辣</td>
        <td>10</td>
        <td>6</td>
        <td>2</td>
        <td>封兽鵺Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>海盗熏肉</td>
        <td>DLC 3</td>
        <td>烤架</td>
        <td>58</td>
        <td>牛肉、蜂蜜、辣椒、黑盐</td>
        <td>肉、大份、传说、力量涌现、特产</td>
        <td>酸</td>
        <td>9</td>
        <td>5.4</td>
        <td>2</td>
        <td>村纱水蜜Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>香煎双菇肉卷</td>
        <td>DLC 3</td>
        <td>油锅</td>
        <td>63</td>
        <td>猪肉、蘑菇、松露</td>
        <td>昂贵、招牌、家常、肉、下酒、重油、灼热、菌类</td>
        <td>凉爽</td>
        <td>9</td>
        <td>5.4</td>
        <td>3</td>
        <td>苏我屠自古Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>白鹿贞松</td>
        <td>DLC 3</td>
        <td>蒸锅</td>
        <td>72</td>
        <td>鹿肉、白果、松子</td>
        <td>昂贵、肉、高级、山珍、文化底蕴、特产</td>
        <td>酸</td>
        <td>12</td>
        <td>7.2</td>
        <td>3</td>
        <td>物部布都Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>什锦天妇罗</td>
        <td>DLC 3</td>
        <td>油锅</td>
        <td>72</td>
        <td>八目鳗、黑毛猪肉、松露、月光草</td>
        <td>昂贵、招牌、家常、下酒、重油、力量涌现、菌类、和风</td>
        <td></td>
        <td>7</td>
        <td>4.2</td>
        <td>3</td>
        <td>苏我屠自古Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>惊吓！大冒险</td>
        <td>DLC 3</td>
        <td>蒸锅</td>
        <td>90</td>
        <td>蘑菇、蜂蜜、幻昙华、奶油</td>
        <td>昂贵、梦幻、猎奇、不可思议、力量涌现、适合拍照、特产</td>
        <td>家常</td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>多多良小伞Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>荷花鱼米盏</td>
        <td>DLC 3</td>
        <td>蒸锅</td>
        <td>94</td>
        <td>极上金枪鱼、露水、并蒂莲、莲子</td>
        <td>昂贵、水产、清淡、传说、梦幻、不可思议、文化底蕴、中华</td>
        <td></td>
        <td>11</td>
        <td>6.6</td>
        <td>4</td>
        <td>霍青娥Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>罗汉上素</td>
        <td>DLC 3</td>
        <td>煮锅</td>
        <td>97</td>
        <td>松露、竹笋、幻昙华、莲子、松子</td>
        <td>昂贵、素、清淡、高级、鲜、凉爽、梦幻、文化底蕴、特产</td>
        <td>肉、辣</td>
        <td>12</td>
        <td>7.2</td>
        <td>4</td>
        <td>村纱水蜜Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>幻想星莲船</td>
        <td>DLC 3</td>
        <td>料理台</td>
        <td>132</td>
        <td>金枪鱼、南瓜、月光草、并蒂莲、莲子</td>
        <td>昂贵、招牌、高级、鲜、生、凉爽、梦幻、不可思议、适合拍照、特产</td>
        <td>猎奇</td>
        <td>13</td>
        <td>7.8</td>
        <td>4</td>
        <td>封兽鵺Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>太极八卦鱼肚</td>
        <td>DLC 3</td>
        <td>煮锅</td>
        <td>136</td>
        <td>极上金枪鱼、萝卜、蘑菇、鸡蛋、白果</td>
        <td>昂贵、水产、清淡、高级、鲜、凉爽、文化底蕴</td>
        <td></td>
        <td>14</td>
        <td>8.4</td>
        <td>4</td>
        <td>物部布都Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>炸番茄条</td>
        <td>DLC 4</td>
        <td>油锅</td>
        <td>26</td>
        <td>西红柿、土豆</td>
        <td>猎奇、不可思议、小巧</td>
        <td>水产</td>
        <td></td>
        <td>3.6</td>
        <td>1</td>
        <td>鬼人正邪Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>红豆大福</td>
        <td>DLC 4</td>
        <td>料理台</td>
        <td>28</td>
        <td>红豆、糯米</td>
        <td>和风、甜、小巧</td>
        <td></td>
        <td></td>
        <td>4.2</td>
        <td>2</td>
        <td>少名针妙丸Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>蜜桃红烧肉</td>
        <td>DLC 4</td>
        <td>油锅</td>
        <td>42</td>
        <td>蜂蜜、桃子、猪肉</td>
        <td>肉、下酒、不可思议、果味</td>
        <td></td>
        <td></td>
        <td>4.8</td>
        <td>2</td>
        <td>鬼人正邪Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>石锅竹笋炖肉</td>
        <td>DLC 4</td>
        <td>煮锅</td>
        <td>42</td>
        <td>竹子、竹笋、猪肉</td>
        <td>肉、家常、饱腹</td>
        <td></td>
        <td></td>
        <td>4.2</td>
        <td>3</td>
        <td>今泉影狼Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>铜锣烧</td>
        <td>DLC 4</td>
        <td>油锅</td>
        <td>40</td>
        <td>红豆、鸡蛋、面粉</td>
        <td>素、和风、甜、特产</td>
        <td>肉</td>
        <td></td>
        <td>3.6</td>
        <td>2</td>
        <td>少名针妙丸Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>梅子茶泡饭</td>
        <td>DLC 4</td>
        <td>煮锅</td>
        <td>32</td>
        <td>梅子、海苔</td>
        <td>家常、和风</td>
        <td></td>
        <td></td>
        <td>2.4</td>
        <td>1</td>
        <td>射命丸文Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>逆转天地！</td>
        <td>DLC 4</td>
        <td>料理台</td>
        <td>124</td>
        <td>竹子、鲜花、梅子、黑毛猪肉、松露</td>
        <td>昂贵、山珍、凉爽、猎奇、菌类、不可思议、梦幻、燃起来了</td>
        <td></td>
        <td></td>
        <td>7.2</td>
        <td>4</td>
        <td>
        </td>
    </tr>
    <tr>
        <td>竹筒粉蒸肉</td>
        <td>DLC 4</td>
        <td>蒸锅</td>
        <td>72</td>
        <td>竹子、露水、黑毛猪肉</td>
        <td>昂贵、肉、家常、山珍</td>
        <td>生</td>
        <td></td>
        <td>5.4</td>
        <td>3</td>
        <td>今泉影狼Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>海胆蒸蛋</td>
        <td>DLC 4</td>
        <td>蒸锅</td>
        <td>112</td>
        <td>海胆、鸡蛋</td>
        <td>昂贵、海味、鲜、适合拍照</td>
        <td>山珍</td>
        <td></td>
        <td>4.2</td>
        <td>3</td>
        <td>射命丸文Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>翠竹迎春</td>
        <td>DLC 4</td>
        <td>蒸锅</td>
        <td>99</td>
        <td>黄瓜、鸡蛋、萝卜、鹿肉、月光草</td>
        <td>昂贵、高级、山珍、招牌、适合拍照、文化底蕴</td>
        <td>猎奇、菌类</td>
        <td></td>
        <td>8.4</td>
        <td>4</td>
        <td>今泉影狼Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>汉宫藏娇</td>
        <td>DLC 4</td>
        <td>煮锅</td>
        <td>115</td>
        <td>八目鳗、豆腐、螃蟹、竹子、露水</td>
        <td>昂贵、水产、高级、传说、中华、猎奇、文化底蕴、汤羹</td>
        <td>重油</td>
        <td></td>
        <td>7.2</td>
        <td>4</td>
        <td>
        </td>
    </tr>
    <tr>
        <td>绿野仙菇</td>
        <td>DLC 4</td>
        <td>煮锅</td>
        <td>24</td>
        <td>香椿、蘑菇</td>
        <td>清淡、文化底蕴、菌类、特产</td>
        <td></td>
        <td></td>
        <td>3.6</td>
        <td>1</td>
        <td>风见幽香Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>香椿煎饼</td>
        <td>DLC 4</td>
        <td>油锅</td>
        <td>30</td>
        <td>香椿、鸡蛋</td>
        <td>招牌、特产</td>
        <td></td>
        <td></td>
        <td>3.6</td>
        <td>1</td>
        <td>梅蒂欣Lv1→Lv2
        </td>
    </tr>
    <tr>
        <td>花鸟风月</td>
        <td>DLC 4</td>
        <td>蒸锅</td>
        <td>78</td>
        <td>鲜花、月光草、奶油</td>
        <td>昂贵、高级、不可思议、梦幻、特产</td>
        <td>灼热、重油</td>
        <td></td>
        <td>5.4</td>
        <td>3</td>
        <td>风见幽香Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>幻想风靡</td>
        <td>DLC 4</td>
        <td>烤架</td>
        <td>185</td>
        <td>洋葱、野猪肉、牛肉、松露、西红柿</td>
        <td>昂贵、肉、重油、饱腹、生、招牌、适合拍照、力量涌现</td>
        <td>凉爽、清淡</td>
        <td></td>
        <td>10.8</td>
        <td>5</td>
        <td>射命丸文Lv3→Lv4
        </td>
    </tr>
    <tr>
        <td>毒瘴花园</td>
        <td>DLC 4</td>
        <td>煮锅</td>
        <td>58</td>
        <td>河豚、梅字、八目鳗、白果</td>
        <td>水产、招牌、猎奇、毒</td>
        <td></td>
        <td></td>
        <td>4.8</td>
        <td>3</td>
        <td>梅蒂欣Lv2→Lv3
        </td>
    </tr>
    <tr>
        <td>幽梦</td>
        <td>DLC 4</td>
        <td>蒸锅</td>
        <td>133</td>
        <td>鲜花、幻昙华、月光草、露水、奶油</td>
        <td>昂贵、高级、清淡、西式、甜、适合拍照、凉爽、梦幻</td>
        <td>肉、下酒、水产</td>
        <td></td>
        <td>7.2</td>
        <td>4</td>
        <td>
        </td>
    </tr>
    <tr>
        <td>小小的甜蜜“毒药”</td>
        <td>DLC 4</td>
        <td>蒸锅</td>
        <td>87</td>
        <td>幻昙华、奶油、葡萄、白果</td>
        <td>昂贵、高级、甜、适合拍照、小巧、梦幻</td>
        <td>肉</td>
        <td></td>
        <td>6</td>
        <td>3</td>
        <td>
        </td>
    </tr>
</tbody>
"""
    return data



